<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="LAPTOP-KKDSPR4V" failures="1" tests="9" name="Test" time="0.408" errors="0" timestamp="2025-08-18T15:43:20 GMT-04:00">
  <testcase classname="packTwo.Annotations" name="DataProviderTest" time="0.023"/>
  <testcase classname="packTwo.Annotations" name="DataProviderTest" time="0.045"/>
  <testcase classname="packTwo.Annotations" name="DataProviderTest" time="0.004"/>
  <testcase classname="packTwo.Annotations" name="FlightBooking" time="0.002"/>
  <testcase classname="packTwo.Annotations" name="OpeningBrowser" time="0.022"/>
  <testcase classname="packTwo.Annotations" name="Demo" time="0.009">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at packTwo.Annotations.Demo(Annotations.java:98)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="packTwo.Annotations" name="MyMethod" time="0.003"/>
  <testcase classname="packTwo.Annotations" name="FlightCancel" time="0.002"/>
  <testcase classname="test.intro" name="Hi" time="0.001"/>
  <testcase classname="test.intro" name="Bye" time="0.0">
    <ignored/>
  </testcase> <!-- Bye -->
  <testcase classname="packTwo.Annotations" name="ErrorneousTest" time="0.0">
    <ignored/>
  </testcase> <!-- ErrorneousTest -->
</testsuite> <!-- Test -->
